### ISSUE TITLE
unexpected errors 

### ISSUE THREAD

**Issue by kalleick** [bloatoo-git/ebay-scraper#1]
I get some errors on a rpi, do you have any hints?

pip install -r requirements.txt
_WARNING: Ignoring invalid distribution -ryptography (/usr/local/lib/python3.7/dist-packages)_

python3 scraper.py
_[WDM] - Downloading: 16.9kB [00:00, 1.62MB/s]
Traceback (most recent call last):
  File "scraper.py", line 130, in <module>
    start()
  File "scraper.py", line 125, in start
    driver = create_driver()
  File "scraper.py", line 109, in create_driver
    service=Service(GeckoDriverManager().install())
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 172, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    creationflags=self.creationflags)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/.wdm/drivers/geckodriver/linux32/0.32/geckodriver'_

**Comment by bloatoo-git** [comment]
First error does not affect the scraper, it pops up when a package is either updated or deleted by pip. 

Second error probably happened due to using an executable that is not meant for your operation system.

**Comment by bloatoo-git** [comment]
Added chromdriver option to the project, you might want to try that.
